language: node_js
node_js:
- "stable"
cache:
 directories:
  - node_modules
before_script:
  - export DATABASE_URL=postgres://wktxteol:otDb5vZWpJVzt4spZvsT0nD7w9iYMzqb@pellefant.db.elephantsql.com:5432/wktxteol
after_success:
  - npm run coveralls
services:
  - postgresql
env:
  - NODE_ENV=test